### ISSUE TITLE
WIP code still references oelint_adv modules

### ISSUE THREAD

**Issue by pombredanne** [priv-kweihmann/oelint-parser#1]
See https://github.com/priv-kweihmann/oelint-parser/commit/dfe068a92fe3a074e82856300b1d559f2e557c92#diff-6666c00665e2889a12a997209efb6d19R4

the import likely needs to be from oelint_parser and not oelint_adv as found by @chinyeungli

**Comment by priv-kweihmann** [comment]
Yeah sorry - should be fixed now (FYI: I did a force push)

**Comment by pombredanne** [comment]
Thanks!
