### ISSUE TITLE
[question] how to get AST or s-expression of a bitbake file by this parser?

### ISSUE THREAD

**Issue by Freed-Wu** [priv-kweihmann/oelint-parser#127]
how to get AST or s-expression of a bitbake file by this parser? TIA!

**Comment by Freed-Wu** [comment]
>  Basically this should do it

`sorted(_stash.GetItemsFor(), lambda k: k.Line)` should be `sorted(_stash.GetItemsFor(), key=lambda k: k.Line)`

`inherit cmake pkgconfig` be parsed to a Variable. Is it a bug?

**Comment by priv-kweihmann** [comment]
> > Basically this should do it
> 
> `sorted(_stash.GetItemsFor(), lambda k: k.Line)` should be `sorted(_stash.GetItemsFor(), key=lambda k: k.Line)`
> 
> `inherit cmake pkgconfig` be parsed to a Variable. Is it a bug?

No it's not `inherit` statements are handled as a special incarnation of `Variable` (see https://github.com/priv-kweihmann/oelint-parser/blob/788689781cc2e326f3bcd8318603adfb261f52a9/oelint_parser/parser.py#L218 and following)

**Comment by priv-kweihmann** [comment]
I assume that your question had been answered - feel free to reopen in case of any questions

**Comment by Freed-Wu** [comment]
Can we get a token stream of a bitbake item? At least to know one token belongs to function name, variable name, etc?

**Comment by Freed-Wu** [comment]
In fact, I try to use oelint-parser to realize [a language server](https://github.com/Freed-Wu/bitbake-language-server/). If the parser can tokenize a bitbake code sentence, we can know the type of token in the cursor.

**Comment by priv-kweihmann** [comment]
In that case I might want to have a look at https://github.com/savoirfairelinux/vscode-bitbake/ - they do offer that kind of thing - for me tokenizing was always a bit out of scope, but I would be happy to see patches enabling such feature.
But it would require major changes how files are parsed and assembled, not sure if that's the right way to go

**Comment by Freed-Wu** [comment]
The vscode-bitbake use tree-sitter, while I use oelint-parser :smile: I am not sure which parser will be better.
