### ISSUE TITLE
[question] Is it possible to get classifier or classifier?

### ISSUE THREAD

**Issue by Freed-Wu** [priv-kweihmann/oelint-parser#142]
How to:

```python
_stash.GetItemsFor(classifier="TaskAssignment" or "Variable")
```

?

Such as:

```python
from oelint_parser.cls_item import Variable, TaskAssignment
_stash.GetItemsFor(classifier=Variable | TaskAssignment)
```
?

**Comment by priv-kweihmann** [comment]
Not yet, but patches are welcome.
https://github.com/priv-kweihmann/oelint-parser/blob/04f14b10d3d72f19b3224fa1891129acb6c72438/oelint_parser/cls_stash.py#L201 would need to changed to allow passing of lists to make it.
