### ISSUE TITLE
Incorrect inherit

### ISSUE THREAD

**Issue by Freed-Wu** [priv-kweihmann/oelint-parser#143]
If a bitbake contains `inherit`, it will be recognized as inherit. Such as:

```bitbake
DEPLOYDIR[doc] = "For recipes that inherit the deploy class, the DEPLOYDIR points to a temporary work area for deployed files."
```

In the following code,

```python
inhname = expand_term(stash, _file, m.group("inhname"))
```

We have:

```python
>>> inhname
'the deploy class, the DEPLOYDIR points to a temporary work area for deployed files."'
```

Is it a bug?

**Comment by priv-kweihmann** [comment]
Indeed it is - https://github.com/priv-kweihmann/oelint-parser/blob/04f14b10d3d72f19b3224fa1891129acb6c72438/oelint_parser/parser.py#L156 needs to be fixed
