### ISSUE TITLE
[Question] Behaviour of rules when parsing .bbappend files with require statements

### ISSUE THREAD

**Issue by MQueiros** [priv-kweihmann/oelint-parser#150]
Hi!

I have a bbappend file that roughly looks like:
```
require path/to/somerequire.inc
require path/to/somerequire2.inc

FILESEXTRAPATHS:prepend := "${THISDIR}/files:"

SRC_URI += "\
    file://something.patch \
```

If I execute some rule for this recipe, oelint just prints "Parsing" and skips the validation:

```bash
$ oelint-adv --relpaths path/to/somefile_%.bbappend --customrules /path/to/container/oelint/rules --rulefile /path/to/container/oelint/rules/rulefile_project_patching.json --constantmods /path/to/container/oelint/rules/project-constants.json
Loaded rules:
        rule.patch.detect
Parsing path/to/somefile_%.bbappend
Parsing path/to/somerequire.inc
Parsing path/to/somerequire2.inc
```

However, the same works fine if I rename the file to .bb extension. Is there any particular reason for this beaviour?

**Comment by priv-kweihmann** [comment]
I found it - it's a bug in the parser - will fix that

**Comment by MQueiros** [comment]
Thanks! I've tried and now it throws errors.

I might have found a related bug though. If I run the rule multiple times, sometimes I get:
```
path/to/somerequire.inc:2:error:
```
Other times I get:
```
path/to/somefile_%.bbappend:5:error:
```

If the `onlyappend` option is used, only the second one will show the errors

**Comment by priv-kweihmann** [comment]
@MQueiros please file a new bug for that at https://github.com/priv-kweihmann/oelint-adv - thanks
