### ISSUE TITLE
Consider not calling subprocesses when building 

### ISSUE THREAD

**Issue by pombredanne** [priv-kweihmann/oelint-parser#24]
The setup.py  is calling pandoc a subprocess. This is not a common practice and eventually Python packaging is moving towards purely declarative manifests.
I would suggest moving the pandoc calls to the build.sh
https://github.com/priv-kweihmann/oelint-parser/blob/75f954f20fc25033610de95ccebb32e6ee08565b/setup.py#L6
Also what is purpose of doing a pandoc conversion from/to markdown?

**Comment by priv-kweihmann** [comment]
This is here for historical reasons and can likely be removed. There were times when pypi refused some not 100% clean and compliant markdown documents, but that was years ago, so I guess it's safe to just read the file instead of invoking pandoc

**Comment by pombredanne** [comment]
FYI, running "twine check" on a built wheel will report any description formatting error.

**Comment by pombredanne** [comment]
Thank you ++
