### ISSUE TITLE
Included bb files are not included

### ISSUE THREAD

**Issue by jmlemetayer** [priv-kweihmann/oelint-parser#242]
Using these recipes:

File `foo.inc`:
```
SRC_URI = "..."
```

File `foo.bb`:
```
require foo.inc
```

File `foo-alt.bb`:
```
require foo.bb
```

Requesting the `SRC_URI` variable from the `foo.bb` file is working well.

But requesting the `SRC_URI` variable from the `foo-alt.bb` file is not working as expected.

---

The issue seems to be in the `Stash.AddFile` method:

```py
    def AddFile(self, _file: str, lineOffset: int = 0, forcedLink: str = None) -> List[Item]:
        _, _ext = os.path.splitext(_file)
        if _file in self.__seen_files and _ext not in [".inc"]:
            return []
    ...
```

From this code we can see that the issue also depends on the order in which files are added (`_file in self.__seen_files`). So if you add `foo.bb` before `foo-alt.bb` you have the issue. But not the other way around.

I think it can be fixed by allowing `.bb` files to be added multiple times:

```diff
-        if _file in self.__seen_files and _ext not in [".inc"]:
+        if _file in self.__seen_files and _ext not in [".inc", ".bb"]:
```

**Comment by priv-kweihmann** [comment]
Including BB files 😬, should be rejected in review 😁.
But I get your point, will have a look into the PR later

**Comment by jmlemetayer** [comment]
Yeah you're right. The typical use case is when building multiple `u-boot` configuration using the `UBOOT_CONFIG` variable.

You have something like that:
```
UBOOT_CONFIG = "alternate"

require u-boot_${PV}.bb
```

`meta-freescale` [was using this](https://git.yoctoproject.org/meta-freescale/tree/recipes-bsp/u-boot/u-boot-fslc-mfgtool_2022.10.bb?h=kirkstone) but it seems to have been updated.
