### ISSUE TITLE
Publish wheel on PyPI

### ISSUE THREAD

**Issue by pombredanne** [priv-kweihmann/oelint-parser#25]
it would be great to also publish a wheel on PyPI

**Comment by priv-kweihmann** [comment]
What would be the advantage of a wheel over sdist for a pure python package like this one?

**Comment by pombredanne** [comment]
> What would be the advantage of a wheel over sdist for a pure python package like this one?

Not running any arbitrary code from a setup.py (security) and a faster installation since it only requires unzipping.
Otherwise, a wheel is **always** recreated by pip on install anyway.

A wheel is also easier to introspect for a static analysis (e.g, with ScanCode Toolkit or the new python-inspector) whereas an sdist requires jumping through a few AST hoops to perform any static analysis and this is more of an art than a science.
A wheel has no such issue.

Here the setup.py executes commands and reads files and neither the long description nor the dependencies can be inferred reliably from the code AST. You have to run it.

In contrast, the wheel contains everything nicely pre-computed.

**Comment by priv-kweihmann** [comment]
Alright looking at it from this perspective, yes it makes sense - will put that on the agenda

**Comment by pombredanne** [comment]
Thank you ++
