### ISSUE TITLE
Variables SPL_BINARY, UBOOT_INITIAL_ENV and UBOOT_SUFFIX are unknown

### ISSUE THREAD

**Issue by pasweistorz** [priv-kweihmann/oelint-parser#267]
Hi,

we're writing a custom recipe for `U-Boot` and use both the `uboot-config.bbclass` as well as `u-boot.inc` from Poky.

We set the `SPL_BINARY` as well as the `UBOOT_SUFFIX` variable in our recipe. They're both used in `uboot-config.bbclass` and documented but we get an OELint error that those variable are unknown. Should they be added to the known variables?

We're also setting the `UBOOT_INITIAL_ENV` variable which is used in `u-boot.inc` but we also get an OELint error that this variable is unknown. Should it be added to the known variables, too? Not sure about this here, because it's not documented.

Thanks for investigating.

**Comment by priv-kweihmann** [comment]
The latest release of oelint-adv names both variables for kirkstone release and up.
If you are using an older release you will need to add

`--constantmods=+my-variables.json`  to the CLI and have a json file `my-variables.json`  with the following content available

```json
{
  "variables": {
  "known": ["SPL_BINARY", "UBOOT_SUFFIX", "UBOOT_INITIAL_ENV"]
}
}
```

And btw it's not an error, but barely an info message that's being reported ;-)
