### ISSUE TITLE
SRC_URI[checksum] is parsed as SRC_URI

### ISSUE THREAD

**Issue by chinyeungli** [priv-kweihmann/oelint-parser#3]
```
SRC_URI[md5sum] = "e5871a3a5c8390557b8033cf19316a55"
SRC_URI[sha256sum] = "084d743bd84d4d9380bac4c71c51e57406dce44f5a69289bb823c903e9b035d8"
```
http://cgit.openembedded.org/openembedded-core/tree/meta/recipes-core/netbase/netbase_6.1.bb

When I use the `x.VarName` for the above example, the tool returns `SRC_URI` instead of  `SRC_URI[md5sum]` and `SRC_URI[sha256sum]` 

Can you differentiate the name so that the checksum and the files/links won't get mixed up?

**Comment by priv-kweihmann** [comment]
I get your point - to me these are variable flags and therefore they are mapped to the Flag attribute.
See https://github.com/priv-kweihmann/oelint-adv/blob/3740ed478477877949ef2160b53f323cc8cdd1ea/oelint_adv/rule_base/rule_var_src_uri.py#L151 for instance.

From a very abstract point of view `SRC_URI` and `SRC_URI[md5sum]` refer to the same and are stored to the same variable entity in the KV store.

This is literally the same behavior used with `PACKAGECONFIG` for example.

What I could add is a property which combines both e.g. x.RawVarName or something like this - would that work for you?

**Comment by chinyeungli** [comment]
`RawVarName` sounds good

**Comment by priv-kweihmann** [comment]
Okay then I'll add it later that day

**Comment by priv-kweihmann** [comment]
Added by forced push to WIP branch
